-- Carga inicial del catálogo (Walt Disney World y Universal Orlando, octubre de 2026).
-- Alturas y cierres tomados de las fuentes publicadas a esa fecha; quedan "sin revisar" hasta que un
-- administrador de la plataforma los verifique contra las páginas oficiales.
INSERT INTO "CatalogEntry" ("id", "kind", "destination", "area", "name", "minHeightIn", "diningStyle", "priceLevel", "notes", "closedFrom", "verifiedAt", "updatedAt") VALUES
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Walt Disney World Railroad', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Jungle Cruise', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Pirates of the Caribbean', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Walt Disney''s Enchanted Tiki Room', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'The Magic Carpets of Aladdin', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Swiss Family Treehouse', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Big Thunder Mountain Railroad', 38, NULL, NULL, 'Reabrió en mayo de 2026 con la altura mínima bajada de 40 a 38 pulgadas.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Tiana''s Bayou Adventure', 40, NULL, NULL, 'Remodelación de rutina; reapertura prevista en diciembre de 2026.', '2026-11-02'::date, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Country Bear Musical Jamboree', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Haunted Mansion', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'The Hall of Presidents', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Seven Dwarfs Mine Train', 38, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Peter Pan''s Flight', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', '"it''s a small world"', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'The Many Adventures of Winnie the Pooh', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Under the Sea ~ Journey of The Little Mermaid', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Enchanted Tales with Belle', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Mickey''s PhilharMagic', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Prince Charming Regal Carrousel', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Dumbo the Flying Elephant', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'The Barnstormer', 35, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Mad Tea Party', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Princess Fairytale Hall', NULL, NULL, NULL, 'Encuentro con princesas.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Pete''s Silly Sideshow', NULL, NULL, NULL, 'Encuentro con personajes.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Town Square Theater', NULL, NULL, NULL, 'Encuentro con Mickey.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Space Mountain', 44, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'TRON Lightcycle / Run', 48, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Buzz Lightyear''s Space Ranger Spin', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Tomorrowland Transit Authority PeopleMover', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Walt Disney''s Carousel of Progress', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Monsters, Inc. Laugh Floor', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Astro Orbiter', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Magic Kingdom', 'Tomorrowland Speedway', 32, NULL, NULL, 'Para manejar solo hay que medir 54 pulgadas (137 cm).', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'Magic Kingdom', 'Happily Ever After', NULL, NULL, NULL, 'Fuegos artificiales nocturnos frente al castillo.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'Magic Kingdom', 'Disney Starlight: Dream the Night Away', NULL, NULL, NULL, 'Desfile nocturno.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'Magic Kingdom', 'Festival of Fantasy Parade', NULL, NULL, NULL, 'Desfile de día.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'Magic Kingdom', 'Mickey''s Magical Friendship Faire', NULL, NULL, NULL, 'Show en el escenario del castillo.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'Magic Kingdom', 'Mickey''s Very Merry Christmas Party', NULL, NULL, NULL, 'Fiesta navideña con entrada aparte, algunas noches de noviembre y diciembre. Confirmar las fechas del año.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'EPCOT', 'Spaceship Earth', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'EPCOT', 'Test Track', 40, NULL, NULL, 'Reabrió en 2025 renovada.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'EPCOT', 'Mission: SPACE', 40, NULL, NULL, 'Versión Verde: 40 pulgadas; versión Naranja (más intensa): 44 pulgadas (112 cm).', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'EPCOT', 'Guardians of the Galaxy: Cosmic Rewind', 42, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'EPCOT', 'Soarin''', 40, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'EPCOT', 'Living with the Land', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'EPCOT', 'Journey Into Imagination with Figment', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'EPCOT', 'The Seas with Nemo & Friends', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'EPCOT', 'Turtle Talk with Crush', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'EPCOT', 'Journey of Water, Inspired by Moana', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'EPCOT', 'Awesome Planet', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'EPCOT', 'Disney and Pixar Short Film Festival', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'EPCOT', 'Frozen Ever After', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'EPCOT', 'Remy''s Ratatouille Adventure', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'EPCOT', 'Gran Fiesta Tour Starring The Three Caballeros', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'EPCOT', 'Canada Far and Wide', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'EPCOT', 'Reflections of China', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'EPCOT', 'Impressions de France', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'EPCOT', 'The American Adventure', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'EPCOT', 'Royal Sommerhus', NULL, NULL, NULL, 'Encuentro con Anna y Elsa.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'EPCOT', 'Luminous The Symphony of Us', NULL, NULL, NULL, 'Show nocturno en la laguna.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'EPCOT', 'EPCOT International Festival of the Holidays', NULL, NULL, NULL, 'Festival navideño, de fines de noviembre a fines de diciembre. Confirmar las fechas del año.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'EPCOT', 'Candlelight Processional', NULL, NULL, NULL, 'Durante el Festival of the Holidays, en el America Gardens Theatre.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'EPCOT', 'Voices of Liberty', NULL, NULL, NULL, 'Coro a capella en The American Adventure.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Hollywood Studios', 'Star Wars: Rise of the Resistance', 40, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Hollywood Studios', 'Millennium Falcon: Smugglers Run', 38, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Hollywood Studios', 'Star Tours – The Adventures Continue', 40, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Hollywood Studios', 'Slinky Dog Dash', 38, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Hollywood Studios', 'Toy Story Mania!', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Hollywood Studios', 'Alien Swirling Saucers', 32, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Hollywood Studios', 'The Twilight Zone Tower of Terror', 40, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Hollywood Studios', 'Rock ''n'' Roller Coaster Starring The Muppets', 48, NULL, NULL, 'Reabrió en 2026 con la nueva temática de los Muppets.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Hollywood Studios', 'Mickey & Minnie''s Runaway Railway', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'Hollywood Studios', 'Fantasmic!', NULL, NULL, NULL, 'Show nocturno; no se hace todas las noches.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'Hollywood Studios', 'Wonderful World of Animation', NULL, NULL, NULL, 'Proyecciones nocturnas sobre el Chinese Theater.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'Hollywood Studios', 'Beauty and the Beast – Live on Stage', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'Hollywood Studios', 'For the First Time in Forever: A Frozen Sing-Along Celebration', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'Hollywood Studios', 'Disney Junior Play and Dance!', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'Hollywood Studios', 'Disney Villains: Unfairly Ever After', NULL, NULL, NULL, 'Show en el Sunset Showcase.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'Hollywood Studios', 'Indiana Jones Epic Stunt Spectacular!', NULL, NULL, NULL, 'Verificar que siga funcionando en las fechas del viaje.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Animal Kingdom', 'Avatar Flight of Passage', 44, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Animal Kingdom', 'Na''vi River Journey', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Animal Kingdom', 'Kilimanjaro Safaris', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Animal Kingdom', 'Expedition Everest – Legend of the Forbidden Mountain', 44, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Animal Kingdom', 'Kali River Rapids', 38, NULL, NULL, 'Te mojás mucho.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Animal Kingdom', 'Gorilla Falls Exploration Trail', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Animal Kingdom', 'Maharajah Jungle Trek', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'DISNEY_WORLD', 'Animal Kingdom', 'Adventurers Outpost', NULL, NULL, NULL, 'Encuentro con Mickey y Minnie.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'Animal Kingdom', 'Festival of the Lion King', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'Animal Kingdom', 'Finding Nemo: The Big Blue... and Beyond!', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'Animal Kingdom', 'Feathered Friends in Flight!', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'Animal Kingdom', 'Zootopia: Better Zoogether!', NULL, NULL, NULL, 'Show 3D en el teatro del Árbol de la Vida (reemplazó a It''s Tough to be a Bug!).', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'DISNEY_WORLD', 'Animal Kingdom', 'Tree of Life Awakenings', NULL, NULL, NULL, 'Proyecciones sobre el Árbol de la Vida al anochecer.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Magic Kingdom', 'Be Our Guest Restaurant', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Magic Kingdom', 'Cinderella''s Royal Table', NULL, 'CHARACTER_DINING'::"DiningStyle", 4, 'Con princesas, dentro del castillo.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Magic Kingdom', 'The Crystal Palace', NULL, 'CHARACTER_DINING'::"DiningStyle", 3, 'Buffet con Winnie the Pooh y sus amigos.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Magic Kingdom', 'The Plaza Restaurant', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Magic Kingdom', 'Tony''s Town Square Restaurant', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Magic Kingdom', 'Liberty Tree Tavern', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Magic Kingdom', 'Jungle Navigation Co. Ltd. Skipper Canteen', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Magic Kingdom', 'Columbia Harbour House', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Magic Kingdom', 'Pecos Bill Tall Tale Inn and Cafe', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Magic Kingdom', 'Cosmic Ray''s Starlight Café', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Magic Kingdom', 'Casey''s Corner', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Magic Kingdom', 'Pinocchio Village Haus', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Magic Kingdom', 'Gaston''s Tavern', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Magic Kingdom', 'The Friar''s Nook', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Magic Kingdom', 'The Lunching Pad', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Magic Kingdom', 'Sleepy Hollow', NULL, 'SNACK'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Magic Kingdom', 'Main Street Bakery', NULL, 'SNACK'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Magic Kingdom', 'Aloha Isle', NULL, 'SNACK'::"DiningStyle", 1, 'Dole Whip.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Magic Kingdom', 'Cheshire Café', NULL, 'SNACK'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Space 220 Restaurant', NULL, 'SIGNATURE'::"DiningStyle", 4, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Space 220 Lounge', NULL, 'LOUNGE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'The Garden Grill Restaurant', NULL, 'CHARACTER_DINING'::"DiningStyle", 3, 'Con Chip y Dale; el restaurante gira.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Coral Reef Restaurant', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, 'Vista al acuario.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Akershus Royal Banquet Hall', NULL, 'CHARACTER_DINING'::"DiningStyle", 3, 'Con princesas, en Noruega.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Le Cellier Steakhouse', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Chefs de France', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Monsieur Paul', NULL, 'SIGNATURE'::"DiningStyle", 4, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'La Crêperie de Paris', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Spice Road Table', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Tutto Italia Ristorante', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Via Napoli Ristorante e Pizzeria', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Teppan Edo', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Shiki-Sai: Sushi Izakaya', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Biergarten Restaurant', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, 'Buffet alemán.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Rose & Crown Dining Room', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'San Angel Inn Restaurante', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'La Hacienda de San Angel', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Nine Dragons Restaurant', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Regal Eagle Smokehouse', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Sunshine Seasons', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Connections Eatery', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Les Halles Boulangerie-Patisserie', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Katsura Grill', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Lotus Blossom Café', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'La Cantina de San Angel', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Yorkshire County Fish Shop', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Sommerfest', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Tangierine Café', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'Kringla Bakeri Og Kafe', NULL, 'SNACK'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'EPCOT', 'La Poutinerie', NULL, 'SNACK'::"DiningStyle", 1, 'Abrió en julio de 2026 cerca del pabellón de Canadá.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Hollywood Studios', 'The Hollywood Brown Derby', NULL, 'SIGNATURE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Hollywood Studios', 'Sci-Fi Dine-In Theater Restaurant', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Hollywood Studios', '50''s Prime Time Café', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Hollywood Studios', 'Hollywood & Vine', NULL, 'CHARACTER_DINING'::"DiningStyle", 3, 'Buffet con personajes; cambian según la temporada.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Hollywood Studios', 'Roundup Rodeo BBQ', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, 'En Toy Story Land.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Hollywood Studios', 'Oga''s Cantina', NULL, 'LOUNGE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Hollywood Studios', 'Docking Bay 7 Food and Cargo', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Hollywood Studios', 'Ronto Roasters', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Hollywood Studios', 'Woody''s Lunch Box', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Hollywood Studios', 'Backlot Express', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Hollywood Studios', 'ABC Commissary', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Hollywood Studios', 'Trolley Car Café', NULL, 'SNACK'::"DiningStyle", 1, 'Starbucks.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Animal Kingdom', 'Tiffins', NULL, 'SIGNATURE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Animal Kingdom', 'Nomad Lounge', NULL, 'LOUNGE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Animal Kingdom', 'Yak & Yeti Restaurant', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Animal Kingdom', 'Rainforest Cafe (Animal Kingdom)', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, 'En la entrada del parque.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Animal Kingdom', 'Tusker House Restaurant', NULL, 'CHARACTER_DINING'::"DiningStyle", 3, 'Buffet con Donald, Daisy, Mickey y Goofy.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Animal Kingdom', 'Satu''li Canteen', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Animal Kingdom', 'Flame Tree Barbecue', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Animal Kingdom', 'Harambe Market', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Animal Kingdom', 'Pizzafari', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Animal Kingdom', 'Yak & Yeti Local Food Cafes', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'The Boathouse', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'Raglan Road Irish Pub and Restaurant', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'Chef Art Smith''s Homecomin''', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'Morimoto Asia', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'Paddlefish', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'The Edison', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'Wolfgang Puck Bar & Grill', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'Jaleo', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'Terralina Crafted Italian', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'STK Steakhouse', NULL, 'TABLE_SERVICE'::"DiningStyle", 4, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'Frontera Cocina', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'City Works Eatery & Pour House', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'Rainforest Cafe (Disney Springs)', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'T-REX', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'Planet Hollywood', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'House of Blues Restaurant & Bar', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'Maria & Enzo''s Ristorante', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'Wine Bar George', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'Enzo''s Hideaway', NULL, 'LOUNGE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'The Polite Pig', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'Chicken Guy!', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'Earl of Sandwich', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'Blaze Fast-Fire''d Pizza', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'Six Ravens', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, 'De Gideon''s; abrió en agosto de 2026.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'Gideon''s Bakehouse', NULL, 'SNACK'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'Ghirardelli Soda Fountain & Chocolate Shop', NULL, 'SNACK'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney Springs', 'Sprinkles', NULL, 'SNACK'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney''s Contemporary Resort', 'Chef Mickey''s', NULL, 'CHARACTER_DINING'::"DiningStyle", 3, 'Buffet con Mickey y sus amigos.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney''s Contemporary Resort', 'California Grill', NULL, 'SIGNATURE'::"DiningStyle", 4, 'Vista a los fuegos de Magic Kingdom.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney''s Polynesian Village Resort', '''Ohana', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, 'Desayuno con personajes (Lilo y Stitch); cena estilo parrilla.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney''s Polynesian Village Resort', 'Kona Cafe', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney''s Grand Floridian Resort & Spa', '1900 Park Fare', NULL, 'CHARACTER_DINING'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney''s Grand Floridian Resort & Spa', 'Narcoossee''s', NULL, 'SIGNATURE'::"DiningStyle", 4, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney''s Grand Floridian Resort & Spa', 'Victoria & Albert''s', NULL, 'SIGNATURE'::"DiningStyle", 4, 'No admite menores de 10 años.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney''s Grand Floridian Resort & Spa', 'Citricos', NULL, 'SIGNATURE'::"DiningStyle", 4, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney''s Grand Floridian Resort & Spa', 'Grand Floridian Cafe', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney''s Riviera Resort', 'Topolino''s Terrace', NULL, 'CHARACTER_DINING'::"DiningStyle", 3, 'Desayuno con personajes; cena sin personajes.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney''s Beach Club Resort', 'Cape May Cafe', NULL, 'CHARACTER_DINING'::"DiningStyle", 3, 'Desayuno con personajes.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney''s Wilderness Lodge', 'Story Book Dining at Artist Point', NULL, 'CHARACTER_DINING'::"DiningStyle", 3, 'Con Blancanieves y los enanos.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney''s Animal Kingdom Lodge', 'Jiko – The Cooking Place', NULL, 'SIGNATURE'::"DiningStyle", 4, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney''s Animal Kingdom Lodge', 'Boma – Flavors of Africa', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, 'Buffet.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney''s Animal Kingdom Lodge', 'Sanaa', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney''s BoardWalk Inn', 'Trattoria al Forno', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney''s Art of Animation Resort', 'Landscape of Flavors', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'DISNEY_WORLD', 'Disney''s Pop Century Resort', 'Everything POP Shopping & Dining', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOPPING', 'DISNEY_WORLD', 'Disney Springs', 'World of Disney', NULL, NULL, 3, 'La tienda Disney más grande.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOPPING', 'DISNEY_WORLD', 'Disney Springs', 'The LEGO Store', NULL, NULL, 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOPPING', 'DISNEY_WORLD', 'Disney Springs', 'Once Upon a Toy', NULL, NULL, 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOPPING', 'DISNEY_WORLD', 'Disney Springs', 'Disney''s Days of Christmas', NULL, NULL, 3, 'Artículos navideños todo el año.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOPPING', 'DISNEY_WORLD', 'Disney Springs', 'Marketplace Co-Op', NULL, NULL, 3, 'Tiendas temáticas de Disney.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOPPING', 'DISNEY_WORLD', 'Disney Springs', 'Marcas de The Landing y Town Center', NULL, NULL, 3, 'Más de 100 tiendas: Zara, Uniqlo, Sephora, Lululemon, Coach, Pandora, entre otras.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOPPING', 'DISNEY_WORLD', 'Orlando', 'Orlando International Premium Outlets', NULL, NULL, 2, 'Outlet en International Drive, cerca de Universal. Tiene Disney Character Warehouse.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOPPING', 'DISNEY_WORLD', 'Orlando', 'Orlando Vineland Premium Outlets', NULL, NULL, 2, 'Outlet de marcas premium, cerca de Disney. Tiene Disney Character Warehouse.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOPPING', 'DISNEY_WORLD', 'Orlando', 'Lake Buena Vista Factory Stores', NULL, NULL, 1, 'Outlet más chico y tranquilo, cerca de Disney.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOPPING', 'DISNEY_WORLD', 'Orlando', 'The Florida Mall', NULL, NULL, 2, 'Uno de los malls más grandes de Florida; tiendas por departamento y M&M''s World.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOPPING', 'DISNEY_WORLD', 'Orlando', 'The Mall at Millenia', NULL, NULL, 4, 'Mall de alta gama (Apple, Louis Vuitton, Macy''s, Bloomingdale''s), cerca de Universal.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOPPING', 'DISNEY_WORLD', 'Orlando', 'ICON Park', NULL, NULL, 2, 'Centro de entretenimiento en International Drive con The Wheel, restaurantes y atracciones; no es un shopping puro.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Despicable Me Minion Mayhem', 40, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'E.T. Adventure', 34, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Fast & Furious – Supercharged', 40, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Harry Potter and the Escape from Gringotts', 42, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'MEN IN BLACK Alien Attack', 42, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Race Through New York Starring Jimmy Fallon', 40, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Revenge of the Mummy', 48, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'The Simpsons Ride', 40, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'TRANSFORMERS: The Ride-3D', 40, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Trolls Trollercoaster', 36, NULL, NULL, 'En DreamWorks Land.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Illumination''s Villain-Con Minion Blast', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Kang & Kodos'' Twirl ''n'' Hurl', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Hogwarts Express – King''s Cross Station', NULL, NULL, NULL, 'Requiere entrada Park-to-Park.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Universal Mega Movie Parade', NULL, NULL, NULL, 'Desfile de día.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'The Bourne Stuntacular', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Animal Actors On Location!', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Universal Orlando''s Horror Make-Up Show', NULL, NULL, NULL, 'Cerrado para renovarse; vuelve en el invierno de 2026.', '2026-05-01'::date, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Universal''s Holiday Parade featuring Macy''s', NULL, NULL, NULL, 'Temporada navideña (mediados de noviembre a fin de diciembre). Confirmar las fechas del año.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'The Amazing Adventures of Spider-Man', 40, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'The Cat in the Hat', 36, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Doctor Doom''s Fearfall', 52, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Dudley Do-Right''s Ripsaw Falls', 44, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Flight of the Hippogriff', 36, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Hagrid''s Magical Creatures Motorbike Adventure', 48, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Harry Potter and the Forbidden Journey', 48, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Jurassic Park River Adventure', 42, NULL, NULL, 'Remodelación larga; reapertura prevista en noviembre de 2026.', '2026-01-05'::date, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Jurassic World VelociCoaster', 51, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'The High in the Sky Seuss Trolley Train Ride!', 36, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'The Incredible Hulk Coaster', 54, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Popeye & Bluto''s Bilge-Rat Barges', 42, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Pteranodon Flyers', 36, NULL, NULL, 'Solo suben adultos acompañando a un chico de entre 36 y 56 pulgadas.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Skull Island: Reign of Kong', 36, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Caro-Seuss-el', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'One Fish, Two Fish, Red Fish, Blue Fish', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Camp Jurassic', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Hogwarts Express – Hogsmeade Station', NULL, NULL, NULL, 'Requiere entrada Park-to-Park.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Hogwarts Always', NULL, NULL, NULL, 'Proyecciones nocturnas sobre el castillo de Hogwarts; en Navidad se reemplaza por un show navideño. Confirmar fechas.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Stardust Racers', 48, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Constellation Carousel', NULL, NULL, NULL, 'Menores de 48 pulgadas, acompañados.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Harry Potter and the Battle at the Ministry', 40, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Mario Kart: Bowser''s Challenge', 40, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Yoshi''s Adventure', 34, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Mine-Cart Madness', 40, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Hiccup''s Wing Gliders', 40, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Dragon Racer''s Rally', 48, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Fyre Drill', NULL, NULL, NULL, 'Te mojás.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Monsters Unchained: The Frankenstein Experiment', 48, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'ATTRACTION', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Curse of the Werewolf', 40, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Le Cirque Arcanus', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOW', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'The Untrainable Dragon', NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Lombard''s Seafood Grille', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Mel''s Drive-In', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Leaky Cauldron', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Louie''s Italian Restaurant', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Today Café', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Krusty Burger', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Fast Food Boulevard', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Bumblebee Man''s Taco Truck', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Classic Monsters Café', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Minion Cafe', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Richter''s Burger Co.', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Moe''s Tavern', NULL, 'LOUNGE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Duff Brewery', NULL, 'LOUNGE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Universal Studios Florida', 'Florean Fortescue''s Ice-Cream Parlour', NULL, 'SNACK'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Mythos Restaurant', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, 'Anunciado su cierre para 2027.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Confisco Grille', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Three Broomsticks', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Hog''s Head', NULL, 'LOUNGE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Captain America Diner', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Café 4', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Comic Strip Café', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Circus McGurkus Café Stoo-pendous', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Green Eggs and Ham Café', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Fire-Eater''s Grill', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Pizza Predattoria', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'The Burger Digs', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Islands of Adventure', 'Croissant Moon Bakery', NULL, 'SNACK'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Atlantic', NULL, 'TABLE_SERVICE'::"DiningStyle", 3, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'The Blue Dragon Pan-Asian Restaurant', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Das Stakehaus', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Mead Hall', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Spit Fyre Grill', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Hooligan''s Grog & Gruel', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Toadstool Cafe', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Café L''air De La Sirène', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'The Oak & Star Tavern', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Pizza Moon', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Star Sui Bao', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Comet Dogs', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Meteor Astropub', NULL, 'LOUNGE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Bar Zenith', NULL, 'LOUNGE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'Epic Universe', 'Frosty Moon', NULL, 'SNACK'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'CityWalk', 'The Toothsome Chocolate Emporium & Savory Feast Kitchen', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'CityWalk', 'The Cowfish Sushi Burger Bar', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'CityWalk', 'Bob Marley – A Tribute to Freedom', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'CityWalk', 'Jimmy Buffett''s Margaritaville', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'CityWalk', 'NBC Sports Grill & Brew', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'CityWalk', 'Hard Rock Cafe Orlando', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'CityWalk', 'Antojitos Authentic Mexican Food', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'CityWalk', 'VIVO Italian Kitchen', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'CityWalk', 'Bigfire', NULL, 'TABLE_SERVICE'::"DiningStyle", 2, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'CityWalk', 'Red Oven Pizza Bakery', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'CityWalk', 'Five Guys', NULL, 'QUICK_SERVICE'::"DiningStyle", 1, 'Abrió en septiembre de 2026.', NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'RESTAURANT', 'UNIVERSAL_ORLANDO', 'CityWalk', 'Voodoo Doughnut', NULL, 'SNACK'::"DiningStyle", 1, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 'SHOPPING', 'UNIVERSAL_ORLANDO', 'CityWalk', 'Universal Studios Store', NULL, NULL, 3, 'Tienda principal de Universal, en CityWalk.', NULL, NULL, CURRENT_TIMESTAMP)
ON CONFLICT ("destination", "area", "name") DO NOTHING;

-- Imperdibles de cada parque: se suman siempre a la propuesta de itinerario. Los administradores los ajustan.
UPDATE "CatalogEntry" SET "mustDo" = true WHERE "area" = 'Magic Kingdom' AND "name" IN ('Seven Dwarfs Mine Train', 'Peter Pan''s Flight', 'Haunted Mansion', 'Pirates of the Caribbean', 'Space Mountain', 'Happily Ever After');
UPDATE "CatalogEntry" SET "mustDo" = true WHERE "area" = 'EPCOT' AND "name" IN ('Frozen Ever After', 'Remy''s Ratatouille Adventure', 'Guardians of the Galaxy: Cosmic Rewind', 'Soarin''', 'Test Track', 'Luminous The Symphony of Us');
UPDATE "CatalogEntry" SET "mustDo" = true WHERE "area" = 'Hollywood Studios' AND "name" IN ('Star Wars: Rise of the Resistance', 'Slinky Dog Dash', 'Mickey & Minnie''s Runaway Railway', 'Toy Story Mania!', 'The Twilight Zone Tower of Terror', 'Fantasmic!');
UPDATE "CatalogEntry" SET "mustDo" = true WHERE "area" = 'Animal Kingdom' AND "name" IN ('Avatar Flight of Passage', 'Na''vi River Journey', 'Kilimanjaro Safaris', 'Expedition Everest – Legend of the Forbidden Mountain', 'Festival of the Lion King');
UPDATE "CatalogEntry" SET "mustDo" = true WHERE "area" = 'Universal Studios Florida' AND "name" IN ('Harry Potter and the Escape from Gringotts', 'Hogwarts Express – King''s Cross Station', 'Revenge of the Mummy', 'Despicable Me Minion Mayhem', 'MEN IN BLACK Alien Attack');
UPDATE "CatalogEntry" SET "mustDo" = true WHERE "area" = 'Islands of Adventure' AND "name" IN ('Hagrid''s Magical Creatures Motorbike Adventure', 'Harry Potter and the Forbidden Journey', 'Jurassic World VelociCoaster', 'The Amazing Adventures of Spider-Man', 'Skull Island: Reign of Kong');
UPDATE "CatalogEntry" SET "mustDo" = true WHERE "area" = 'Epic Universe' AND "name" IN ('Harry Potter and the Battle at the Ministry', 'Mario Kart: Bowser''s Challenge', 'Stardust Racers', 'Hiccup''s Wing Gliders', 'Monsters Unchained: The Frankenstein Experiment');
