-- Tipos de reserva específicos por marca (paquete Disney World, tickets Universal, etc.).
ALTER TYPE "ItemType" ADD VALUE IF NOT EXISTS 'DISNEY_WORLD_PACKAGE';
ALTER TYPE "ItemType" ADD VALUE IF NOT EXISTS 'DISNEY_WORLD_HOTEL';
ALTER TYPE "ItemType" ADD VALUE IF NOT EXISTS 'DISNEY_WORLD_TICKETS';
ALTER TYPE "ItemType" ADD VALUE IF NOT EXISTS 'DISNEYLAND_PACKAGE';
ALTER TYPE "ItemType" ADD VALUE IF NOT EXISTS 'DISNEYLAND_TICKETS';
ALTER TYPE "ItemType" ADD VALUE IF NOT EXISTS 'UNIVERSAL_PACKAGE';
ALTER TYPE "ItemType" ADD VALUE IF NOT EXISTS 'UNIVERSAL_HOTEL';
ALTER TYPE "ItemType" ADD VALUE IF NOT EXISTS 'UNIVERSAL_TICKETS';
ALTER TYPE "ItemType" ADD VALUE IF NOT EXISTS 'UNIVERSAL_EXPRESS';
ALTER TYPE "ItemType" ADD VALUE IF NOT EXISTS 'DISNEY_CRUISE';
